sed -i 's/mocks_NR_1$/SAR11_Surface_1_CladeIa-stag_31.5-even_9.11/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_6$/OCS155_a_CandActinomarina-stag_15.8-even_9.11/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_10$/Thaumarchaea_MGI_a_Nitrosopumilus-stag_9.01-even_9.11/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_11$/OCS155_b_CandActinomarina-stag_9.01-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_2$/Prochlorococcus-stag_6.76-even_9.11/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_0$/SAR86_a_Gamma-stag_4.5-even_9.11/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_12$/AEGEAN-169_Alpha-stag_2.25-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_3$/SAR116_a_Alpha-stag_2.25-even_9.11/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_9$/Euryarchaea_MGII-stag_1.8-even_9.11/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_5$/Flavobacteria-stag_1.8-even_9.11/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_7$/SAR202_a_Chloroflexi-stag_1.8-even_9.11/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_8$/Planctomycetes_Blastopirellula-stag_1.8-even_9.11/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_13$/SAR116_b_Alpha-stag_1.8-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_4$/Marine_Group_A_aka_SAR406-stag_1.35-even_9.11/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_16$/Verrucomicrobia-stag_0.901-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_15$/SAR86_b_Gamma-stag_0.901-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_19$/Pseudohongiella_Gamma-stag_0.901-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_17$/SAR92_Gamma-stag_0.901-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_18$/Flavobacteria_Formosa-stag_0.901-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_26$/Thaumarchaea_MGI_b_Nitrosopumilus-stag_0.901-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_14$/Flavobacteria_NS9-stag_0.901-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_21$/Rhodobacteriaceae_Alpha-stag_0.676-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_20$/SAR86_c_Gamma-stag_0.676-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_22$/Flavobacteria_NS5-stag_0.45-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_23$/SAR86_d_Gamma-stag_0.22-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_24$/SAR116_c_Alpha-stag_0.113-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
sed -i 's/mocks_NR_25$/SAR202_b_Chloroflexi-stag_0.113-even_0/g' mocks_all_non-redundant-renamed-ref.fasta
